Improve conversion from scalars to native types (#391)
* implemented low-level conversion functions from a scalar to null/bool/int

* optimized the way of scanning scalars

* implemented conversion function from scalars to floating point type values

* added bounds check into atoi()

* added test cases for scalar_conv.hpp, removing from_string tests

* conditionally use std::from_chars for conversions from scalars to floating point numbers if available

* added descriptions in scalar_conv.hpp

* fixed compile errors

* added test cases for missed lines/branches & add in-source docs in scalar_scanner.hpp

* fixed name collision between arg and index in atoi_dec_*() functions

* fixed clang-sanitizer errors & reconsidered its ignorant options

* fixed undefined reference to conv_limits::{min|max}_value_chars_dec

* dropped long double support in atof() due to portability issue